[package]
name = "version_tool"
version = "0.1.0"
authors = ["ziqings <ziqings-zqu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#pcre2 = "*"
#pcre2-sys = "*"
regex = "*"
rustc-serialize = "*"
